### ISSUE TITLE
Tag dla IE

### ISSUE THREAD

**Issue by zapalagrzegorz** [senorhollow/barbjitsu_project#1]
Co to znaczy:    
`<meta http-equiv="X-UA-Compatible" content="ie=edge">`?

**Comment by senorhollow** [comment]
to pozostałość po "klepanym" wcześniej kodzie, nie wrzuciłem jeszcze commita w którym wszystko wyczyściłem, co do samego pytania - tag miał odpowiadać za poprawne wyświetlanie się strony internetowej w starszych wersjach przeglądarek od microsoftu

**Comment by zapalagrzegorz** [comment]
Dokładnie. Pytam dlatego, że zdarzyło mi się, że ten tag był używany! Jeden z klientów używał IE, i strona mu się źle renderowała z powodu wewnętrznych ustawień. Pomógł ww. tag dot. zgodności. Jedna jeszcze rzecz. Nie znalazłem źródła cytatu, ale wg Microsoftu

> If you are using the X-UA-Compatible META tag you want to place it as close to the top of the page's HEAD as possible.  Internet Explorer begins interpreting markup using the latest version. When Internet Explorer encounters the X-UA-Compatible META tag it starts over using the designated version's engine. This is a performance hit because the browser must stop and restart analyzing the content.

Stąd błędnie założyłem, że powinien być na samej górze i juz bym spór zakładał czy również przed ustawieniem kodowania. Niepotrzebnie:
> The X-UA-Compatible header isn't case sensitive; however, it must appear in the header of the webpage (the HEAD section) before all other elements except for the title element and other meta elements.
Czyli wszystko w porządku. Musi być przed innymi niż <meta>
